library(testthat)
library(rfars)

test_that("the right file name is generated by make_filename()", {
    expect_equal(make_filename(2014), "accident_2014.csv.bz2")
})

test_that("fars_read_years return a NULL if the file is missing", {
    expect_equal(fars_read_years(2014), list(NULL))
})
